name: dbt CI simple

on:
  push:
    branches: [main]

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Run dbt
        run: |
          dbt deps
          dbt build